"""Init FW

Revision ID: 2140c70565d5
Revises: 
Create Date: 2018-09-13 15:20:20.091561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2140c70565d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rglfw', sa.Column('rglfw_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_rglfw_rglfw_date'), 'rglfw', ['rglfw_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rglfw_rglfw_date'), table_name='rglfw')
    op.drop_column('rglfw', 'rglfw_date')
    # ### end Alembic commands ###
